### ISSUE TITLE
Add a footer.

### ISSUE THREAD

**Issue by ADRE9** [ADRE9/bunk-manager-mern#10]

**Comment by promaroy** [comment]
Can I work on this as a part of GSSOC '21?

**Comment by ADRE9** [comment]
Yes, you are welcome to do so!

**Comment by Anjali041** [comment]
Can you assign this issue to me ? I am a participant of GSSoC'21

**Comment by ADRE9** [comment]
You can fork and work on it. We can merge your PR if we like. So go ahead !

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by micksharma** [comment]
Can I work on this issue.

**Comment by ADRE9** [comment]
Yes @sahildotexe @micksharma @promaroy go ahead fork the project and return with a good PR. All the best

**Comment by srk224** [comment]
Can i also work on it and create my pull request @ADRE9 ??
I am a gssoc'21 participant
