### ISSUE TITLE
Make the Footer Mobile responsive

### ISSUE THREAD

**Issue by Sanyam2000-dot** [ADRE9/bunk-manager-mern#100]
**Deliverables:**

- [ ] Make the footer mobile responsive.
- [ ] Make the icon size a little bigger.

**Screenshots**
![Screenshot (233)](https://user-images.githubusercontent.com/53525430/113404014-21cf3480-93c5-11eb-9227-c428cf5f377b.png)

**Comment by FireQueen-3010** [comment]
Can I work on this as part of gssoc'21?

**Comment by Sanyam2000-dot** [comment]
Sure, Go ahead.

**Comment by FireQueen-3010** [comment]
Icon size in the sense social icons right? @Sanyam2000-dot

**Comment by FireQueen-3010** [comment]
All the styling right now is done only in inline format which means to add media queries for small-screens, I need to create a separate css file for that and transfer all the predefined styling for the footer to that as well and assign classes. So, should I proceed? Please suggest @Sanyam2000-dot

**Comment by ADRE9** [comment]
@FireQueen-3010 actually the participant who made this was not aware of Material UI and wanted to contribute. So we had let him do it. But for now you need to use the syntax of Material UI. No inline styling. Use JSS. [Documentation](https://material-ui.com/).
