### ISSUE TITLE
Renaming the attendance page and displaying subjects and labs which student has on the particular day.

### ISSUE THREAD

**Issue by Sanyam2000-dot** [ADRE9/bunk-manager-mern#102]
**Deliverables:**

- [ ] Rename the attendance page to Today.
- [ ] Display only those subjects and labs which a student has on that day.

**Screenshots**
![BunkManager-Today](https://user-images.githubusercontent.com/53525430/113469920-fe60c400-946e-11eb-9a9a-f9aadff809b4.png)

**Comment by Artistic18** [comment]
I would like to work on this issue. @Sanyam2000-dot

**Comment by Artistic18** [comment]
@Sanyam2000-dot @ADRE9  The default cards doesn't  contains any days values, it would be better if someone could add edit those values, it would be easier for me to work.

**Comment by ADRE9** [comment]
Actually there is a days feature. But since for the first time the user gets template subjects , it is empty. As soon as the user starts editing subject it becomes necessary to add the days to it. And then you can show it in the today's page. We are imagining a page where a new registered user will be introduced to time table so taht the user can easily add and change time table. If you want to work on it before. Talk to @kunaljain0212 or @Sanyam2000-dot  , they will help you to create an issue and and work on it.

**Comment by Artistic18** [comment]
@ADRE9 Ok thanks I got your point

**Comment by Artistic18** [comment]
@ADRE9 @Sanyam2000-dot check if this is the needed functionality.

https://user-images.githubusercontent.com/16490253/113484574-ad7cba00-94c6-11eb-940d-aedb337701d9.mp4

**Comment by ADRE9** [comment]
Yes Exactly ! Change the Route from "attendance" to "today". And Classes and Labs to Today's Classes and Today's Labs respectively.

**Comment by Artistic18** [comment]
@ADRE9 Ok sure

**Comment by Artistic18** [comment]
@ADRE9 should the Today Page contain the default cards?

**Comment by ADRE9** [comment]
No only what's today.

**Comment by Artistic18** [comment]
@ADRE9 how this looks? 
And as per Route I think we should make another issue if we want to update route to '/today' as it will need a lot of changes to many files. Currently it is routed to '/' and I think it's better to keep that.
![Untitled](https://user-images.githubusercontent.com/16490253/113485513-7f4da900-94cb-11eb-9196-dce99eb041e2.png)

**Comment by ADRE9** [comment]
No by Route I meant the Link component that is now labelled as Attendance.

**Comment by Artistic18** [comment]
@ADRE9 Can you please help me with this part, I can't seem to get it.

**Comment by Artistic18** [comment]
@ADRE9 ok I got what you're trying to say thanks, working on that

**Comment by Artistic18** [comment]
@ADRE9 @Sanyam2000-dot kindly review the PR.

**Comment by Sanyam2000-dot** [comment]
Looks good to me. @ADRE9 please review it.
