### ISSUE TITLE
Adding a dropdown menu for every card element.

### ISSUE THREAD

**Issue by Sanyam2000-dot** [ADRE9/bunk-manager-mern#103]
**Deliverables:**

- [ ] Adding the dropdown menu for each card element(subjects and labs)

**Screenshots**
![BunkManager-Subjects](https://user-images.githubusercontent.com/53525430/113471959-8e0d6f00-947d-11eb-95ac-d83b5ffb38cc.png)

**Comment by Artistic18** [comment]
Can I work on this issue?

**Comment by Sanyam2000-dot** [comment]
Sure, Go ahead! @Artistic18

**Comment by Artistic18** [comment]
@Sanyam2000-dot what should be the different options other than change pic in dropdown?

**Comment by Artistic18** [comment]
PC - 
![1](https://user-images.githubusercontent.com/16490253/113473921-36c1cb80-948a-11eb-96a5-4a789bdd9de9.png)
![2](https://user-images.githubusercontent.com/16490253/113473922-37f2f880-948a-11eb-8aa6-e03561b652ff.png)
Mobile -
![3](https://user-images.githubusercontent.com/16490253/113473925-39242580-948a-11eb-80cc-23c4e2e0c664.png)

**Comment by Sanyam2000-dot** [comment]
Go ahead and create a pull request.

**Comment by Artistic18** [comment]
@Sanyam2000-dot kindly review the PR.
