### ISSUE TITLE
[Design] Create the subject details page.

### ISSUE THREAD

**Issue by Sanyam2000-dot** [ADRE9/bunk-manager-mern#105]
**Deliverables:**

- [ ]  Design subject details page in FIGMA or Adobe XD
- [ ] Used the color palette that is used in the project

**Screenshots**
![BunkManager-Details](https://user-images.githubusercontent.com/53525430/113472455-03c70a00-9481-11eb-90e8-09775c74d235.png)

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by Sanyam2000-dot** [comment]
> Can I work on this issue under GSSoC'21? Kindly assign it to me.

Sure, go ahead.

**Comment by ADRE9** [comment]
@Saptar001 has  a nice idea of graph implementation. Can you please upload the video here @Saptar001 .

**Comment by Saptar001** [comment]
https://user-images.githubusercontent.com/76171314/113605741-ae4b5280-9664-11eb-827e-64c54d5ca4c0.mp4

@ADRE9

**Comment by ADRE9** [comment]
Thanks @Saptar001 , so this graph needs to be designed for the subject details page for each particular subject.

**Comment by ADRE9** [comment]
And @AshuKV  you need to show me the design to review.

**Comment by Artistic18** [comment]
@ADRE9 For developing the graph I think we can use this library https://chartkick.com/react

**Comment by ADRE9** [comment]
@Artistic18 yes but this issue is all about designing , implementing would come much later.

**Comment by Artistic18** [comment]
Yes I just provided a reference how the graph might actually look, so it becomes easy while designing.

**Comment by Sanyam2000-dot** [comment]
@AshuKV can you report your progress?

**Comment by SAHU-01** [comment]
@Sanyam2000-dot  I would like to work on this issue ,please let me know about all the details I should keep in mind while designing and I will submit a sample by tonight,if you approve of the sample outline,I'd submit a prototype within 2 days!

**Comment by Sanyam2000-dot** [comment]
> @Sanyam2000-dot  I would like to work on this issue ,please let me know about all the details I should keep in mind while designing and I will submit a sample by tonight,if you approve of the sample outline,I'd submit a prototype within 2 days!

I'm so sorry @SAHU-01 but this issue is already assigned. You can choose any other issue and work on it.

**Comment by ADRE9** [comment]
Hey @SAHU-01 can you just DM me on the discord server. Actually we have fixed a UI/UX designer for the design issues to work on but if you are eager to work on you can collaborate with her and work together , but if you are willing to take this page to design she'll guide you and this issue will be give to you.

**Comment by deeptea22** [comment]
Hey, I would like to work on this :)

**Comment by SAHU-01** [comment]
> Hey @SAHU-01 can you just DM me on the discord server. Actually we have fixed a UI/UX designer for the design issues to work on but if you are eager to work on you can collaborate with her and work together , but if you are willing to take this page to design she'll guide you and this issue will be give to you.

sure I'd love to work on it,and if someone guides me ,it's even better!
