### ISSUE TITLE
Creating an issue template for the project

### ISSUE THREAD

**Issue by AnjaliPatle** [ADRE9/bunk-manager-mern#11]
Hey. I was wondering if it would be helpful to add an issue template. If you plan on having a template for this project then please assign me this issue as I'd like to work on it as a GSSOC'21 participant.

**Comment by ADRE9** [comment]
Sure that would be great!

**Comment by micksharma** [comment]
I want to work on this issue.

**Comment by ADRE9** [comment]
Hold Your PRs for somedays until we organize a meet and explain the repos to you

**Comment by ADRE9** [comment]
@AnjaliPatle start your PRs.  1 more day to complete
