### ISSUE TITLE
Redesign the UI with better color schemes and UX.

### ISSUE THREAD

**Issue by kunaljain0212** [ADRE9/bunk-manager-mern#112]
**Deliverables:**
Add the deliverables with their description here.
Before beginning to design a new UI you can comment here some of your previous works in UI/UX and based on that we'll assign this issue. We'll try to get on a meet with whoever is assigned with this issue to explain the deliverables.

**Screenshots**
Add any relevant screenshots to show how the elements looks or works currently/how the enhanced element should look or function.

**Comment by deeptea22** [comment]
Hey, I would like to work on this issue. I have previously designed these for two other GSSOC projects :
https://www.figma.com/file/XsiAbwGmeozKOJQ6my4G4X/Tutoring-App?node-id=0%3A1
https://www.figma.com/file/HeGwdICyeIfZEarbu4tM5I/Roll-Call?node-id=0%3A1

Thank you :)

**Comment by rishabhborn2win** [comment]
I would like to improve the UI with better colour schema.

Some of the design links:-
<b>muckIN</b>:-
https://www.figma.com/file/jM68FhhIhiMvjyHnXomAy3/muckIn?node-id=0%3A1
<b>Tambola Numbers</b>
https://www.figma.com/file/VLrpNQlYbncINJ3ESUxB0g/Tambola?node-id=0%3A1

**Comment by ADRE9** [comment]
Check out the color schemes right now https://www.figma.com/file/dQbGpSkclUec07vztFkUEV/Material-Design-UI-kit-Components-library-Community?node-id=120%3A1658 and come up with your work. We will accept a PR with better UI/UX.

**Comment by deeptea22** [comment]
Hey @ADRE9 This is what i've come up with : 
https://www.figma.com/file/rgJ3ACTdteJxiRVmPu5wsi/Bunk-Manager?node-id=0%3A1

**Comment by ADRE9** [comment]
There are two points I need to point out
1.The signup and signin card that is used in our current website won't change. So you need to change your design to keep our cards.
2. I need to see how you imagine the design for mobile version.

I really loved your concept and a little design fix and we can confirm it.Great Job.

**Comment by deeptea22** [comment]
Ok thank you! Will come up with the updated one soon :)

**Comment by deeptea22** [comment]
https://www.figma.com/file/rgJ3ACTdteJxiRVmPu5wsi/Bunk-Manager?node-id=0%3A1
@ADRE9 Here's the updated one. Please let me know if there are any changes :)

**Comment by ADRE9** [comment]
@deeptea22 I just liked your designs, though it needs loads of touch ups. Gradient looks okeish but, can you create duplicates of the pages with different color pages to compare. And keep in mind having the dark mode also. And yes for each page you need a light theme , dark theme and mobile view (and yes each page will be a level 3 issue). 

P.S :-loved your designs, complete it with touchups and we can merge each page with a level 3.

**Comment by rishabhborn2win** [comment]
> https://www.figma.com/file/rgJ3ACTdteJxiRVmPu5wsi/Bunk-Manager?node-id=0%3A1
> @ADRE9 Here's the updated one. Please let me know if there are any changes :)

Your design is awesome!

**Comment by deeptea22** [comment]
> @deeptea22 I just liked your designs, though it needs loads of touch ups. Gradient looks okeish but, can you create duplicates of the pages with different color pages to compare. And keep in mind having the dark mode also. And yes for each page you need a light theme , dark theme and mobile view (and yes each page will be a level 3 issue).
> 
> P.S :-loved your designs, complete it with touchups and we can merge each page with a level 3.

@ADRE9 @kunaljain0212 @Mustafiz04 @Sanyam2000-dot Sure, will do the changes suggested. Please let me know what are all the different pages i need to do :)

**Comment by deeptea22** [comment]
> > https://www.figma.com/file/rgJ3ACTdteJxiRVmPu5wsi/Bunk-Manager?node-id=0%3A1
> > @ADRE9 Here's the updated one. Please let me know if there are any changes :)
> 
> Your design is awesome!

Thank you! 🤗

**Comment by deeptea22** [comment]
@kunaljain0212 @Mustafiz04 @Sanyam2000-dot I've come up with a few different colours and their respective dark modes. 
https://www.figma.com/file/rgJ3ACTdteJxiRVmPu5wsi/Bunk-Manager
If you could please let me know what are all the different pages i would need to do, then i can start working on those as well.
Thank you :)

**Comment by Mustafiz04** [comment]
@deeptea22 all look very interesting.
Let confirm with the admin and then confirm with you.

**Comment by ADRE9** [comment]
Listen @deeptea22 designs looks awesome. The fonts needs some attention. And about different colors. Use gradients like you have used. And in Dark mode instead of using colors try using different shades of black and instead of shadow you can use thin white borders. Also glassmorphism can go well with your designs. Rest all you've nailed it.

**Comment by deeptea22** [comment]
ok will make the changes :)

**Comment by deeptea22** [comment]
Hey @ADRE9! I have implemented gradients with all the colours. In dark modes, I have used different shades of black for the fields and also replaced shadows with white borders. Have tried glassmorphism in the 'Name' field of all the gradient designs. Please take a look and if it is okay i will do it for other fields as well. For fonts do you have something in mind?
https://www.figma.com/file/rgJ3ACTdteJxiRVmPu5wsi/Bunk-Manager?node-id=0%3A1

**Comment by ADRE9** [comment]
Hey @deeptea22  it looks better , the font needs some consistency, can I collaborate with you on this project. I need some specific changes that I can't speak of. You can DM link to me to edit on the discord.
