### ISSUE TITLE
Display alternate message when there are no classes/labs available for the current day.

### ISSUE THREAD

**Issue by Artistic18** [ADRE9/bunk-manager-mern#114]
**Deliverables:**
 Currently nothing is displayed if a particular day has no class/lab.
![Untitled](https://user-images.githubusercontent.com/16490253/113608523-54e52280-9668-11eb-94f0-0c9005c30490.png)

- [x] Display an alternate message like 'There are no class/lab today.'

**Comment by ADRE9** [comment]
Can you work on the footer issue #101 .And moreover the footer is fixed as in mobile I am  not bale to view the lab cards. Check that out.

**Comment by ADRE9** [comment]
@Artistic18  do you want to work one some level 3? The time table page would have 2-3 level 3 issues and I guess you can handle it well. Dm me in the discord server.

**Comment by Artistic18** [comment]
@ADRE9 Sure I can give them a try.

**Comment by subhangi2731** [comment]
please assign me this too

**Comment by kunaljain0212** [comment]
@subhangi2731 any updates?

**Comment by subhangi2731** [comment]
Yes @kunaljain0212 I am sending a pr now

**Comment by subhangi2731** [comment]
I have worked
