### ISSUE TITLE
Google signup and login is to be activated

### ISSUE THREAD

**Issue by rishabhborn2win** [ADRE9/bunk-manager-mern#116]
**Deliverables:**
Add the deliverables with their description here.
- [X] Firstly the user has to signup user using google login
- [X] Then the user can directly login app using the google login.

**Screenshots**
:( Sorry No SS.
https://user-images.githubusercontent.com/55771529/113730131-3ab54e00-9715-11eb-95f7-c9edc6ca8e9f.mov

**Comment by rishabhborn2win** [comment]
Please assign me this task.
we can have a meet for the oAuth API related details.

**Comment by ADRE9** [comment]
So yes we have some more things to make sure. First of all sign up with Google will provide us with email id and name. And for the rest we still need to ask user for details. So you need to do both if you are doing Google OAuth. Create two level 3 issues. And if you want to work I can assign both of it to you.
So it's your call either both or none of them. You can still create the issue though. Half job would create problems in understanding codes for other participants.

**Comment by rishabhborn2win** [comment]
> So yes we have some more things to make sure. First of all sign up with Google will provide us with email id and name. And for the rest we still need to ask user for details. So you need to do both if you are doing Google OAuth. Create two level 3 issues. And if you want to work I can assign both of it to you.
> So it's your call either both or none of them. You can still create the issue though. Half job would create problems in understanding codes for other participants.

Yes I will complete this task. Kindly assign this task to me.
I didn't understand what you are asking o Create two level 3 issue please make it more clear.

**Comment by ADRE9** [comment]
Yes the first is to integrate Google OAuth and 2nd to use te email and name we get from Google to be used in filling the form that contains regdId, password etc.

**Comment by rishabhborn2win** [comment]
Ok sure.

**Comment by rishabhborn2win** [comment]
<img width="422" alt="Screenshot 2021-04-10 at 8 34 11 AM" src="https://user-images.githubusercontent.com/55771529/114256539-8f87eb80-99d7-11eb-8721-cb14703efacd.png">


There is no message where its indicating that mongo is connected successfully or not
