### ISSUE TITLE
Add Timetable Page.

### ISSUE THREAD

**Issue by Artistic18** [ADRE9/bunk-manager-mern#117]
Deliverables: 
- [x] Create a basic Timetable page. Design and other functionalities to be added in future issues.
- [x] This page should always display after a user has registered for the first time. 

Template:
![SAVE_20210406_151239](https://user-images.githubusercontent.com/16490253/113748188-d058d980-9725-11eb-9a5d-56affa486aec.jpg)

**Comment by ADRE9** [comment]
So are you gonna work on it?

**Comment by Artistic18** [comment]
@ADRE9 yes working on it

**Comment by Artistic18** [comment]
@ADRE9 

https://user-images.githubusercontent.com/16490253/113762831-a1972f00-9736-11eb-921f-34a3a01c7796.mp4

**Comment by ADRE9** [comment]
@Artistic18  I mean don't make Time Table a tab . We will attach a button to access it somewhere from the page. After the registration the user needs to be verify email and then needs to set the time table for initial setup and then he gets redirected to the home page. So yeah you need to set up the pragmatic navigation and add a save button for dummy savings and redirecting after saving the subjects. Got it?

**Comment by ADRE9** [comment]
Later you can start working on add subjects form (level 3), time table(level 3) and the implementation of adding subject to time table (level 3) issue each.

**Comment by Artistic18** [comment]
@ADRE9 yes got it, I just created a tab to verify the redirects and make it easier to work, will remove it later after completing it's functionality and assign it to the button.

**Comment by Artistic18** [comment]
@ADRE9 is the email verification page done?

**Comment by ADRE9** [comment]
No, issues coming soon. But you can start working on these things. It's gonna take time till then it will be ready.

**Comment by Artistic18** [comment]
@ADRE9 ok sure

**Comment by Artistic18** [comment]
@ADRE9 is this ok?
Added a redux state to disable the header elements.

https://user-images.githubusercontent.com/16490253/113845469-2de73780-97b3-11eb-9f93-a45b6b8bad6c.mp4

**Comment by ADRE9** [comment]
Perfect.👍🏻

**Comment by Artistic18** [comment]
@ADRE9 shall I raise a PR?

**Comment by ADRE9** [comment]
Sure do it. Comment the lines you have attached, in the redux it gets messy otherwise. Which file have you used or created a new one. I guess for this new file is required , since rest all reducers are dealing with the APIs.
