### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by Sristi27** [ADRE9/bunk-manager-mern#119]
**Deliverables:**
Add the deliverables with their description here.
- [ ] We can add a contact us page
- [ ] Proper form with proper UI and colour pallete

**Comment by ADRE9** [comment]
So you want to design the Contact page right? Stick to the palette and share the link with me to review.

**Comment by Sristi27** [comment]
Do assign it to me!

**Comment by Mustafiz04** [comment]
Yes you can @Sristi27
