### ISSUE TITLE
Redesigning Landing Page 

### ISSUE THREAD

**Issue by anhushree** [ADRE9/bunk-manager-mern#126]
**Is your feature request related to a problem? Please describe.**
The UI layout of the webpage can be improvised. Adding more visual elements to it will make it look better

**Describe the solution you'd like**
Create a landing page for the website where the user can navigate to Home, About, Login slides.
Has UI layouts for Website, Mobile with two themes- light and dark.
The design will be done using UI software- Figma, AdobeXD. 

**Describe alternatives you've considered**
Can have Contact Us, Queries, Profile slides

**Comment by anhushree** [comment]
@ADRE9 I would like to work on this issue as a GSSoc'21 participant. Kindly assign it to me.

**Comment by ADRE9** [comment]
Sure Go ahead , make sure you mention the color palette and the primary, secondary and tertiary colors.

**Comment by anhushree** [comment]
@ADRE9 Will, you be assigning GSSoC labels and level labels for this issue? Cuz I want to contribute as a GSSoC participant.

**Comment by anhushree** [comment]
App Design:
https://www.figma.com/file/sd8f5twPt3iCrMGPX2izFa/BunkManagerApp?node-id=0%3A1

Web Design:
https://www.figma.com/file/yv7szBhuylAeMShJoNY7oF/BUNK-MANAGER?node-id=0%3A1
