### ISSUE TITLE
Design - Login Page - Web And Mobile.

### ISSUE THREAD

**Issue by deeptea22** [ADRE9/bunk-manager-mern#127]
Hey, @ADRE9 I have created the design for the login page for the website. Please let me know where i should include the design image files, should i create a separate folder?
Also please assign this to me, so that i can make the PR. Thank you :)

**Comment by ADRE9** [comment]
No all you need to do is to attach the link to the figma in the readme file. And also attach a screenshot of PC, Mobile and the Dark mode here in the comment.

**Comment by deeptea22** [comment]
PC-Light Mode
![image](https://user-images.githubusercontent.com/67323371/115541982-6449aa00-a2bd-11eb-806f-5bb45cae0b6a.png)

PC-Dark Mode
![image](https://user-images.githubusercontent.com/67323371/115542060-7deaf180-a2bd-11eb-92cb-96d2aeba0beb.png)

Mobile 
![image](https://user-images.githubusercontent.com/67323371/115542250-b68acb00-a2bd-11eb-9281-939d6397601e.png)
