### ISSUE TITLE
Create the Landing Page in React.

### ISSUE THREAD

**Issue by ADRE9** [ADRE9/bunk-manager-mern#131]
**Deliverables:**
Add the deliverables with their description here.

- [x] Follow the design from [Here](https://www.figma.com/file/yv7szBhuylAeMShJoNY7oF/BUNK-MANAGER?node-id=0%3A1)
- [x] Use Material UI to create the page.

**Screenshots**
![Screenshot (259)](https://user-images.githubusercontent.com/49809895/115610879-122d7680-a307-11eb-97d4-15da56ccc7f1.png)

**Comment by ADRE9** [comment]
Illustrations will be available by tomorrow.

**Comment by ashuvssut** [comment]
is that navbar not yet created?

That navbar is not a material-ui AppBar component...
are we allowed to use css to do that? I can completely create that same design using css

**Comment by ADRE9** [comment]
@ashuvssut material ui is our go to library for this app. So that navbar needs to be created using material ui and yes it can be created by over riding some values. So yes if you can create something close using the material-ui I can assign you this page.

**Comment by ashuvssut** [comment]
I think there will a lots of makeStyles overriding. I have to use that MUI Appbar component only right? Or is there any other component? I can find only appbar component upon googling

So, in this issue, contributor has to work on that landing page and that Navbar too?

**Comment by ashuvssut** [comment]
Is that navbar fixed
 or
will it move up and hide iteself

**Comment by ADRE9** [comment]
For now create the rest of webpage , Nav bar needs another issue. You can create one issue, I'll add tags.

**Comment by ADRE9** [comment]
You want to be assigned to it?

**Comment by ashuvssut** [comment]
> For now create the rest of webpage , Nav bar needs another issue. You can create one issue, I'll add tags.

alright! i was just confirming this

Plz assign me this issue. 

I can connect to you on discord to get the illustrations
or
You can add  a  link to those resources here only

**Comment by ADRE9** [comment]
Ilustrations added at client/src/assets/svg/ , all the best brother.

**Comment by kunaljain0212** [comment]
Closing this issue @ADRE9
