### ISSUE TITLE
UI Design for AboutsUs page

### ISSUE THREAD

**Issue by anhushree** [ADRE9/bunk-manager-mern#134]
**Is your feature request related to a problem? Please describe.**
Creating an AboutUs page for the website using the latest Design software like Figma, AdobeXD, etc.

**Describe the solution you'd like**
Would like to create an AboutUs page where the User can get details about the product as well as get to know the product developers and contributors, the footer can have contact us and queries elements.

**Comment by anhushree** [comment]
@Mustafiz04 @ADRE9 I would like to work on this issue as a GSSoC'21 participant. Kindly include the respected tags and I would like to get a span of 3 - 4 days for completing this design.

**Comment by ADRE9** [comment]
Sure Go Ahead.

**Comment by VishalPatil18** [comment]
Can I work on this @ADRE9 under GSSoC21?

**Comment by ADRE9** [comment]
Yes. Please.
