### ISSUE TITLE
Send email when user sign up using node-mailer

### ISSUE THREAD

**Issue by Mustafiz04** [ADRE9/bunk-manager-mern#14]

**Comment by udaymittal7** [comment]
Hey, can I take this task?

**Comment by Mustafiz04** [comment]
Hey!
Yes go for it.

**Comment by ADRE9** [comment]
Hold Your PRs for somedays until we organize a meet and explain the repos to you

**Comment by udaymittal7** [comment]
Yeah sure.

**Comment by udaymittal7** [comment]
I have implemented the code for this. Should I review it with you before making a pull request?

**Comment by Mustafiz04** [comment]
Have you run it in your local host??
Is it run perfectly??

If yes make a PR with proper name and with new branch.
We will receive it.

**Comment by udaymittal7** [comment]
The changes I am making in the code after running on vs code and then running the server is not reflected on the site running on my localhost. Not this email one specifically, but any change I make.  What should I do?

Also I am getting this error after running npm run dev

![image](https://user-images.githubusercontent.com/72199778/110789431-e1810880-8295-11eb-9493-d89d2bda6121.png)
![image](https://user-images.githubusercontent.com/72199778/110789503-f52c6f00-8295-11eb-95b5-1960cfd19928.png)
![image](https://user-images.githubusercontent.com/72199778/110789563-05444e80-8296-11eb-8e9f-38fa296dfb55.png)

**Comment by udaymittal7** [comment]
I have checked the implementation of my code in one of my project and it is working just fine. Should I make the PR and then you can review it?

**Comment by Mustafiz04** [comment]
Have you run `npm install` in your terminal??
See this is mongo error there are some syntax mistake.
Go through the line where MongooseError start.

**Comment by Mustafiz04** [comment]
First run successfully on your local then make PR.
It will be better for both of us.

**Comment by ADRE9** [comment]
Can you show @Mustafiz04  a live version before making a PR? If @Mustafiz04 agrees you can make a PR to the branch-1.

**Comment by udaymittal7** [comment]
Yes I did run npm install in both client folder and the main folder as mentioned by you.  I think the process.env.URI is not defined which is causing the issue.

![image](https://user-images.githubusercontent.com/72199778/110797787-7fc59c00-829f-11eb-991e-493eccfd7cbb.png)

Should i connect it with my mongoDB to test it?

**Comment by udaymittal7** [comment]
@ADRE9 Yes, I will only make the PR on his confirmation. I also don't want to burden you by making the PR for reviewing it.

**Comment by udaymittal7** [comment]
My changes are still not be able to reflect when I run my code and start the server. Though the mongoose error is gone.
What to do @Mustafiz04

**Comment by udaymittal7** [comment]
Hey I made the PR for it and it got merged. Please check.
