### ISSUE TITLE
Failed to find .env file at path: ./configs/dev.env

### ISSUE THREAD

**Issue by subhangi2731** [ADRE9/bunk-manager-mern#151]
**Describe the bug**
The .env file has been removed, probably due to a bad commit. It should be added for running of server

**To Reproduce**

**Expected behavior**
Server should run

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by subhangi2731** [comment]
@kunaljain0212 @ADRE9 I want to work on this please assign me this

**Comment by Artistic18** [comment]
Are you facing any issue while running the app because it's working fine for me.
Moreover it's a bad practice to commit .env variables because it contains sensitive data like api_keys. Therefore I don't think the .env file has been removed due to a bad commit. It is ignored in the gitignore.

**Comment by subhangi2731** [comment]
@Artistic18 In package.json under npm run dev command, ./configs/dev/.env is mentioned which does not exist in the project. I am well aware that env contains confidential information. @kunaljain0212 please assign me this

**Comment by subhangi2731** [comment]
@Mustafiz04 @kunaljain0212 please assign me
