### ISSUE TITLE
Frontend: Add a 404 NOT FOUND page

### ISSUE THREAD

**Issue by Subham142** [ADRE9/bunk-manager-mern#152]
If the user goes to another path the page 404 page is shown

**Comment by Subham142** [comment]
@kunaljain0212  please assign it to me

**Comment by kunaljain0212** [comment]
@Subham142  good job, but we actually went through a UI redesign and the links to new UI designs are available in the readme file, please go through those designs once and see if you can create a 404 page similar to the new designs and colour theme.

**Comment by kunaljain0212** [comment]
Hi @Subham142 did you update the design?
