### ISSUE TITLE
Google Sign In Not Working

### ISSUE THREAD

**Issue by GuptaTanisha** [ADRE9/bunk-manager-mern#155]
**Describe the bug**
The Google Sign-In is not working 

**To Reproduce**

1. Go to the Homepage
2. Click on Sign In using Google

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by GuptaTanisha** [comment]
Please Assign this to me.

**Comment by ADRE9** [comment]
How are you thinking of implementing this one? @GuptaTanisha

**Comment by GuptaTanisha** [comment]
@ADRE9 I can use [this doc](https://medium.com/dailyjs/mern-stack-implementing-sign-in-with-google-made-easy-9bfdfe00d21c) as refernce

**Comment by lopamudra2000** [comment]
Hey @ADRE9  I want to work on this issue.Can you assign it to me?

**Comment by ADRE9** [comment]
Hey @lopamudra2000 we were thinking of integrating the firebase authentication with our current Webapp . Will you be able to integrate the firebase google sign in with the front end and then we will need to integrate it with the backend to verify the token that we get from the firebase ?

**Comment by lopamudra2000** [comment]
Yes @ADRE9 I'd do .I'll require the client api key.

**Comment by ADRE9** [comment]
Ok I'll set up a temporary client api key and upload in a file called as firebase.js. Will that be ok?

**Comment by lopamudra2000** [comment]
I have made the PR adding the feature of client side authentication of firebase google login. Please Review PR #161 . My checks are getting failed.

**Comment by ADRE9** [comment]
Yes we have actually updated the package manager from npm to yarn .
