### ISSUE TITLE
Redesign the UI/UX of the App for landing page

### ISSUE THREAD

**Issue by ADRE9** [ADRE9/bunk-manager-mern#20]
We need to rethink the UI/UX of the MERN stack app for the desktop. So we need experienced designers who are good at using FIGMA or Adobe XD. And create an overall UI of the App so that we can create and modify components according to it. @Mustafiz04 and @Sanyam2000-dot  can you look for experienced participants for it? Contact me as soon as you get one.

**Comment by Saptar001** [comment]
Can you assign me the task of redesigning the UI/UX for the GSSoC,21 ?

**Comment by ADRE9** [comment]
Ok for now start with the design of front page. But the Sign In and Sign Up card stays as it is. You can change color though to match your design. @Saptar001

**Comment by srk224** [comment]
Can I also work on this and pitch up my idea?

**Comment by ADRE9** [comment]
Sure ! Btw @Saptar001 and @srk224 what you both can do is you both can collaborate together. It'll make things go faster. And at a particular moment you can invite me to Figma or Adobe XD and I can review you designs and suggest.

**Comment by srk224** [comment]
Yes..We can definitely do that
btw is there any discord server or anything through which we can communicate better?
@Saptar001 how should I contact you??.

**Comment by Saptar001** [comment]
@srk224 you can dm me at discord .
Username : Saptarshee(P)#6619

**Comment by ADRE9** [comment]
Hold Your PRs for somedays until we organize a meet and explain the repos to you

**Comment by srk224** [comment]
@Saptar001 I am not able to find you on discord...can you please share your general username rather than the nickname for your gssoc server!!

**Comment by Saptar001** [comment]
@srk224 Its my username, dont know why its not showing, you can share your username so that I could dm you.

**Comment by srk224** [comment]
@Saptar001 my username-Shahrukh💣#9724
Message me on discord

**Comment by bhubesh757** [comment]
@Saptar001 Are you working only on the UI/Ux , or Else making The code for that , If not after completing the ui design i can make the code for that. @Saptar001 @srk224 If You agree with this ! @ADRE9 Look into this Contibution

**Comment by ADRE9** [comment]
@bhubesh757 start working on it and send me the link to FIGMA or AdobeXd . I will review your design.

**Comment by srk224** [comment]
@ADRE9 Can you give me a brief idea on what exactly we have to design !?

**Comment by ADRE9** [comment]
The total UI of the landing page for first. Since the UI of the app would be and overload. The better UI will be implemented and if I don't like it. I'll hire one from outside.

**Comment by srk224** [comment]
So basically we have to design a whole new website and if possible the show the new features which can be added in the wireframes?

**Comment by farseenmanekhan1232** [comment]
Can I work on Enhancements of the UI of the website , like Fonts , Colors etc. ??

**Comment by farseenmanekhan1232** [comment]
> Can I work on Enhancements of the UI of the website , like Fonts , Colors etc. ??

like in this case 
![Screenshot 2021-03-17 192654](https://user-images.githubusercontent.com/67449931/111479228-c7906b80-8756-11eb-8c70-2089a980d043.png)
I changed the Logo font to Century Gothic

Likewise I'll try to improve the UI of the websites

**Comment by ADRE9** [comment]
@srk224 @farseenmanekhan1232 @Saptar001 you all can have a talk and make a consistent design. You can distribute the design of each page . I want it to be perfect and consistent. Each design will carry a level3 tag so yes I wont compromise a bit.

**Comment by farseenmanekhan1232** [comment]
So should we implement the design in project itself or in Figma and Later implement the design in the project and Request for a PR??

**Comment by farseenmanekhan1232** [comment]
Hey , @srk224 &  @Saptar001  , can we collaborate??

**Comment by ADRE9** [comment]
Use Figma for now , I'll review it. @Saptar001  is working on the landing page. Chose one page each.and be consistent to use same font and color palette everywhere. Better talk and decide.

**Comment by farseenmanekhan1232** [comment]
Ok
