### ISSUE TITLE
The logo for the Instagram needs to be replaced with that of Google

### ISSUE THREAD

**Issue by ADRE9** [ADRE9/bunk-manager-mern#22]
The OAuth logo for Instagram needs to be replaced with that of the Google. Participants contact @Sanyam2000-dot for guidance.

**Comment by Quickbeasts51429** [comment]
hey can I take up the task?

**Comment by Sanyam2000-dot** [comment]
> hey can I take up the task?
> 

Sure. Go ahead!

**Comment by ADRE9** [comment]
Hold Your PRs for somedays until we organize a meet and explain the repos to you

**Comment by ADRE9** [comment]
Start your PR.

**Comment by Muditxofficial** [comment]
@ADRE9 Can you assign me this, if anybody not working on it.

**Comment by ADRE9** [comment]
Sure , go ahead.
