### ISSUE TITLE
Footer can be Improved

### ISSUE THREAD

**Issue by srk224** [ADRE9/bunk-manager-mern#26]
Hey!
I just noticed that the footer of the website can be improved and ill be able to do it!
can you please assign me this task under gssoc'21?

**Comment by srisatya12** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by Mustafiz04** [comment]
Hey!
Yes go for it @srk224 
If he not done in 1-2 then @srisatya1197 will go for it.

**Comment by srk224** [comment]
Thanks for assigning the issue.......................I am on it
Will get it done by tomorrow!!

**Comment by ADRE9** [comment]
@srisatya1197  you too go ahead and come back with your version of PR. The better one gets PR merged. Make a good one.

**Comment by srisatya12** [comment]
Thank you Sir

**Comment by ADRE9** [comment]
Hold Your PRs for somedays until we organize a meet and explain the repos to you

**Comment by ADRE9** [comment]
Start your PRs.

**Comment by srk224** [comment]
I have created my PR. Now the footer looks like this
![2021-03-11 (1)](https://user-images.githubusercontent.com/63584405/110774706-1c7a4080-8284-11eb-8e9d-35a20195a46c.png)

**Comment by srk224** [comment]
I have created my PR. The footer is centre aligned and looks better
![2021-03-11 (1)](https://user-images.githubusercontent.com/63584405/110774998-6f53f800-8284-11eb-9922-a076b74532bc.png)

**Comment by icoderharshit** [comment]
Kindly assign this issue to me as well @ADRE9 sir ! Because, I want to add responsiveness to the footer also along with a better design.

**Comment by ADRE9** [comment]
There's this issue when in mobile view the footer overlaps over the bottom navigation. Fix that and do another PR @srk224

**Comment by ADRE9** [comment]
> I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

Start making your PR then, 1day of time given else I'll have to reassign.

**Comment by Arshanshagarwal** [comment]
I would like to contribute to this issue. Please assign me this task as a part of GSSoC'21.

**Comment by Arshanshagarwal** [comment]
I would like to contribute to this issue. Please assign me this task as a part of GSSoC'21.

**Comment by sparshsharma2510** [comment]
I would love to work on this issue. @ADRE9 Can you please assign it to me?
