### ISSUE TITLE
Logo name hides in small screen

### ISSUE THREAD

**Issue by AmeyaJain-25** [ADRE9/bunk-manager-mern#27]
![Screenshot from 2021-03-09 21-28-12](https://user-images.githubusercontent.com/66305085/110500022-cc359e00-811e-11eb-83ad-7a348a4f6e17.png)

The logo name is not perfectly adjusted when the browser width get's less or in nearby tab mode due to the navbar items.
I would like to solve this issue under GSSoC 21' as being a participant.
Please assign me this issue

**Comment by Abhishek765** [comment]
@AmeyaJain-25 If you stuck in this try to find the font size and change the font-size to 100% and it will be fixed I tried that and it works  👍 Go ahead I am also a Gssoc'21 participant btw😅

**Comment by AmeyaJain-25** [comment]
Thanks.
I'm new to GSSoC.
Do I have to wait before I get assigned to this issue

**Comment by ADRE9** [comment]
Just a day or two and we will be starting to assign it to participants. Till then you can try to fix and and pitch up your code.

**Comment by SARVESHKHANDELWAL** [comment]
Can you please assign me this issue I will fix that.

**Comment by AmeyaJain-25** [comment]
> Just a day or two and we will be starting to assign it to participants. Till then you can try to fix and and pitch up your code.

Ok Sure.
I'll keep the solution ready.
Will make the PR once you assign me the issue.

**Comment by ADRE9** [comment]
Start your PRs. I'll give you 1 day.
