### ISSUE TITLE
The headings in the Subject page look unattractive.

### ISSUE THREAD

**Issue by aishwarya0816** [ADRE9/bunk-manager-mern#29]
@ADRE9 The headings: CLASSES and LABS, look unattractive. Please allow me to enhance their look. I am a GSSOC'21 Participant and this would be a good first issue for me. Thankyou! 

![Screenshot (73)](https://user-images.githubusercontent.com/55185952/110617348-98f51c80-81bb-11eb-8bc7-f0e5384dba22.png)

**Comment by ADRE9** [comment]
We are closed for some days. We'll surely assign you as soon as we are open for PRs.

**Comment by aishwarya0816** [comment]
@ADRE9 Can you now assign me to work on this issue?

**Comment by ADRE9** [comment]
Go ahead @aishwarya0816 !

**Comment by aishwarya0816** [comment]
Okay! But it doesnt show me as ' assigned' yet? @ADRE9

**Comment by ADRE9** [comment]
I was to tell mentors to assign people from tomorrow. But you know it's the time you are asking for that made me assign it right now. All the best!
