### ISSUE TITLE
Change default favicon

### ISSUE THREAD

**Issue by dig9074vijay** [ADRE9/bunk-manager-mern#30]
Hey!
I noticed that we still have the default **favicon** that comes with React boilerplate code. I would to like to change it to the one that fits our theme as a GSSOC`21 participant. 
@ADRE9

**Comment by ADRE9** [comment]
@dig9074vijay ok go ahead.

**Comment by dig9074vijay** [comment]
Thanks @ADRE9 ! I'll add it shortly
