### ISSUE TITLE
Add labels to mobile navigation icons.

### ISSUE THREAD

**Issue by lopamudra2000** [ADRE9/bunk-manager-mern#37]
![screenshot](https://user-images.githubusercontent.com/63795546/110808942-7a218380-82aa-11eb-866e-2c265cca09ae.jpeg)
For clarity we can add labels to icons in bottom nav for mobile view.

**Comment by lopamudra2000** [comment]
@ADRE9  and mentors , I am gssoc21 participant can you assign this issue to me.

**Comment by ADRE9** [comment]
Sure go ahead!

**Comment by lopamudra2000** [comment]
@ADRE9  please keep branch-1 parallel to Master. I'm Facing conflicts while making PR to Branch-1.

**Comment by ADRE9** [comment]
Branch-1 has been removed and replaced with the dev all changes were minor and not breaking.
