### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by ADRE9** [ADRE9/bunk-manager-mern#4]
Update the readme with the file structures and more pictures and snaps of applications.

**Comment by Devenkapoor7303** [comment]
Can I work on this issue as a part of GSSOC 21

**Comment by ADRE9** [comment]
Yes, Go ahead. Make a beautiful and interactive one!

**Comment by Devenkapoor7303** [comment]
Okay

**Comment by ADRE9** [comment]
Add separate sections for MacOS and Windows.

**Comment by Devenkapoor7303** [comment]
Okay I will do that

**Comment by Devenkapoor7303** [comment]
But can u tell me some differences becoz i have never used MacOs

**Comment by ADRE9** [comment]
Ok , do it for Windows fir now.

**Comment by Devenkapoor7303** [comment]
Okay @ADRE9

**Comment by micksharma** [comment]
I want to work on this issue.

**Comment by ADRE9** [comment]
Go ahead. Can you write commands for MacOs as well? Make a good and an interactive one.

**Comment by micksharma** [comment]
@ADRE9 ok I write commands for MacOS as well
