### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [ADRE9/bunk-manager-mern#45]
**Deliverables:**
Add the deliverables with their description here.
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by sahilempire** [comment]
I want to work on this issue, **Please assign me**.

Thanking you

**Comment by Sanyam2000-dot** [comment]
Go ahead @rohank2502
