### ISSUE TITLE
Headings of the Attendance page

### ISSUE THREAD

**Issue by aishwarya0816** [ADRE9/bunk-manager-mern#46]
**Deliverables:**
- [ ] The formatting of headings of the Attendance Page should be similar to those in the Subjects page.
Please assign me for it.

**Screenshots**
CURRENT
![Screenshot (73)](https://user-images.githubusercontent.com/55185952/110991741-0a3ef600-839b-11eb-9e17-459f218d4138.png)

EXPECTED
![Screenshot (75)](https://user-images.githubusercontent.com/55185952/110991906-3a869480-839b-11eb-88b7-0be8a661ac13.png)

**Comment by Sanyam2000-dot** [comment]
> **Deliverables:**
> 
> * [ ]  The formatting of headings of the Attendance Page should be similar to those in the Subjects page.
>   Please assign me for it.
> 
> **Screenshots**
> CURRENT
> ![Screenshot (73)](https://user-images.githubusercontent.com/55185952/110991741-0a3ef600-839b-11eb-9e17-459f218d4138.png)
> 
> EXPECTED
> ![Screenshot (75)](https://user-images.githubusercontent.com/55185952/110991906-3a869480-839b-11eb-88b7-0be8a661ac13.png)

Go ahead!
