### ISSUE TITLE
working with mongoose means working with promises

### ISSUE THREAD

**Issue by abhay27chauhan** [ADRE9/bunk-manager-mern#47]
### Proposal

if you are working with mongoose, means you are working with promises. So, you need to handle promise. This is an easy fix but good for long term. 

I suggest instead of this:

- **mongoose.connect(process.env.URI, {
  useNewUrlParser: true,
  useCreateIndex: true,
  useUnifiedTopology: true,
  autoIndex: true,
  useFindAndModify:false,
});**

You should do this:

`
const connectDB = async () => {

    try{

            const conn = await mongoose.connect(process.env.URI, {useNewUrlParser: true, useUnifiedTopology: true});
            console.log(`MongoDB Connected: ${conn.connection.host}`)
    }catch(err){

            console.log(err)
            process.exit(1)
    }
}

connectDB();
`

It is good practice :)

**Comment by abhay27chauhan** [comment]
I am a participant of GSSOC21, so please let me know if this is a valid proposal

**Comment by Mustafiz04** [comment]
@abhay27chauhan Yes go for it. I am assigning to you.
Also add event listener like

`
mongoose.connection.on('connected', () => {
        console.log('[Info] DB Connection Established')
    })
`

for connection, reconnection, disconnected and closed.

Have any doubt fell free to ask

**Comment by ADRE9** [comment]
@abhay27chauhan it has been two days and you'll be given one day more to contribute else we will reassign it to someone.
