### ISSUE TITLE
Add the sender email and add a suitable subject

### ISSUE THREAD

**Issue by udaymittal7** [ADRE9/bunk-manager-mern#49]
Adding the sender mail in nodemailer function to adrenine13@gmail.com and adding relevant subject.

**Comment by udaymittal7** [comment]
Hey, when I upstream the master branch, the utils folder doesn't contain email,js file in which I have to update changes. How to resolve this?

**Comment by ADRE9** [comment]
Try pulling once. I don't see a reason why it doesn't contain the email.js file else.

**Comment by ADRE9** [comment]
Complete it fast , I have another job for you.

**Comment by udaymittal7** [comment]
I will complete it by tomorrow evening. Thanks for the patience.
