### ISSUE TITLE
Oauth for Instagram and Google needs to be attached.

### ISSUE THREAD

**Issue by ADRE9** [ADRE9/bunk-manager-mern#5]
The oauth functionality of Instagram and Facebook has not been attached yet

**Comment by Gyaniultimate** [comment]
Can I work on this part to add oauth functionality for facebook? as a part of GSSOC'21

**Comment by ADRE9** [comment]
Yes go ahead!

**Comment by namansamra** [comment]
can i work on this for  Oauth funtionality as a part of GSSOC'21? please assign it to me.

**Comment by ADRE9** [comment]
Okay @namansamra @Gyaniultimate we are planning to ditch the Insta OAuth and introduce Google instead. So @Gyaniultimate  can go for Facebook and @namansamra you can go for Google OAuth.

**Comment by namansamra** [comment]
@ADRE9 we need to implement the Oauth for the "Sign In" functionality only? because for the "Sign Up" process user has to fill some more detail other than email and password  like department semester etc.

**Comment by ADRE9** [comment]
For now just attaching the code for OAuth will do. We can implement the Sign Up with Google later. After Sign Up with google we will redirect the user to another page and make them fill the rest of the details. We will also attach the confirm with email feature. @namansamra

**Comment by ADRE9** [comment]
Hold Your PRs for somedays until we organize a meet and explain the repos to you

**Comment by ADRE9** [comment]
Okay you all can start making you PR. 3 days of time given else we would reassign.

**Comment by namansamra** [comment]
Please assign me this. I have implemented the sign In feature and wanted some discussion /help for sign Up feature.

**Comment by ADRE9** [comment]
@namansamra the google button will be merged soon and after that you can start making your PR. But we have some issues we need to discuss first. I have assigned you the issue, so after having a meet you can work on it.

**Comment by ADRE9** [comment]
go ahead @namansamra

**Comment by namansamra** [comment]
@ADRE9 I have some doubts about the flow . Is there any gitter chat or  something like that where I can ask you about that?

**Comment by ADRE9** [comment]
Discord server GSSOC bunk-manager channel
