### ISSUE TITLE
Adding various security features

### ISSUE THREAD

**Issue by udaymittal7** [ADRE9/bunk-manager-mern#51]
Setting various HTTP headers using helmet
Data sanitization against no SQL injection and XSS
Rate limiter so the server won't get overload
Preventing parameter pollution

If you find it relevant, please assign me.
Please add the relevant GSSOC tags too.

**Comment by Mustafiz04** [comment]
Yes go for it @udaymittal7

**Comment by udaymittal7** [comment]
Created a PR at #53. Please check.
