### ISSUE TITLE
Confusing button name in signup section

### ISSUE THREAD

**Issue by ashirbad29** [ADRE9/bunk-manager-mern#59]
**Deliverables:**
Add the deliverables with their description here.
- [ ] The signup button should be named Register instead of signup because it's causing a bit of confusion

**Screenshots**
![image](https://user-images.githubusercontent.com/46968256/111147679-befe3080-85b0-11eb-8762-654577abee8f.png)

**Comment by ashirbad29** [comment]
can i work on this issue as a gssoc student

**Comment by GurshehzadSingh** [comment]
Im a gssoc participant..can i work on this issue

**Comment by ADRE9** [comment]
@ashirbad29 ok go ahead.

**Comment by ADRE9** [comment]
Since @ashirbad29  is not active I am reassigning it to @GurshehzadSingh . Go ahead.

**Comment by Artistic18** [comment]
Is this issue still available?

**Comment by GurshehzadSingh** [comment]
@Artistic18 It is assigned to me.. I have already completed the issue.. I just need to make a PR tomorrow after clearing some doubt.

**Comment by Artistic18** [comment]
@GurshehzadSingh Sure no problem.

**Comment by GurshehzadSingh** [comment]
I have corrected the name to Register.. Kindly merge the PR
