### ISSUE TITLE
Clicking on the edit button reloads the page.

### ISSUE THREAD

**Issue by ADRE9** [ADRE9/bunk-manager-mern#6]
clicking on the edit button of the subject reloads the page for the first time

**Comment by Muditxofficial** [comment]
Hello, @ADRE9  for admin it is not reloading, please give more details.

**Comment by ADRE9** [comment]
Can you try it out on mobile and confirm.

**Comment by Muditxofficial** [comment]
Yeah i found out too many errors occur in mobile.I will look into this tomorrow.

**Comment by micksharma** [comment]
I want to work on this issue.

**Comment by Muditxofficial** [comment]
@micksharma yeah you can do it.

**Comment by ADRE9** [comment]
Hold Your PRs for somedays until we organize a meet and explain the repos to you.

**Comment by nikhilgupta2001** [comment]
I'd like to work on it as a GSSOC'21 participant.Please assign it to me

**Comment by ashirbad29** [comment]
I can work on this issue as a GSSOC participant

**Comment by ADRE9** [comment]
@ashirbad29 go ahead. @Mustafiz04 can you assign him. I am traveling and mobile doesn't have the feature of assigning people.
