### ISSUE TITLE
[Need] PR template

### ISSUE THREAD

**Issue by Aryamanz29** [ADRE9/bunk-manager-mern#63]
**Is your feature request related to a problem? Please describe.**
PR template

**Describe the solution you'd like**
I want to add a PR template

**Comment by Aryamanz29** [comment]
I would like to work on this issue, Please add labels and kindly assign it to me

**Comment by ADRE9** [comment]
Go ahead !

**Comment by Aryamanz29** [comment]
Please Add `gssoc21` label to this `Issue and PR` @ADRE9
