### ISSUE TITLE
Signup form validation error

### ISSUE THREAD

**Issue by garvitgupta13** [ADRE9/bunk-manager-mern#66]
**Describe the bug**
There is no validation for semester in signup form

**To Reproduce**
1. Go to 'signup'
2. set semester as 950
3. It will be accepted

**Expected behavior**
It should display error while receiving an invalid semester

**Screenshots**
![image](https://user-images.githubusercontent.com/70805691/111380701-b4d05500-86ca-11eb-8426-48017a685d15.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by garvitgupta13** [comment]
Please assign me this issue under gssoc21 label

**Comment by ADRE9** [comment]
Sure. Go ahead.
