### ISSUE TITLE
We can add "Get in touch section" in the footer.

### ISSUE THREAD

**Issue by ASHISH-GITHUB2495** [ADRE9/bunk-manager-mern#69]
**Deliverables:**
We can have a footer with Get in touch section ... you have option to fill name, email and message which will go directly to the admin.
Like the screenshot i have attach ...
if you like the idea  I would like to contribute as GSSOC'21 participant.

**Screenshots**
![Screenshot (15)](https://user-images.githubusercontent.com/57385079/111492140-6d95a300-8762-11eb-8c3a-39a94b739c86.png)

**Comment by ASHISH-GITHUB2495** [comment]
Can I start working on it sir... ?

**Comment by ADRE9** [comment]
Go ahead! Use material ui elements please. We are sticking to the material ui library. Link :- https://material-ui.com/

**Comment by ASHISH-GITHUB2495** [comment]
Thank you for assigning this task to me... I will give my best.

**Comment by ADRE9** [comment]
And yes @ASHISH-GITHUB2495 you can use Formik for react forms and Yup for validation, this will ease your jobs with handling forms.

**Comment by ADRE9** [comment]
And yes @ASHISH-GITHUB2495 you can use Formik for react forms and Yup for validation, this will ease your jobs with handling forms.

**Comment by ASHISH-GITHUB2495** [comment]
### Sir check it please ...am i going right or not?
And It will take time sir... is time madatory?
I am first time contributer ... so bit slower than other

Actually I am not very much familier with material-UI things... but i am expanding my knowledge and applying it...
.. thanks a lot sir.


![Screenshot (16)](https://user-images.githubusercontent.com/57385079/111777384-3d244500-88d9-11eb-9e12-53ef6dda443e.png)

**Comment by ADRE9** [comment]
You are doing great! Take your time.

**Comment by ASHISH-GITHUB2495** [comment]
Thank you ... sir

**Comment by ASHISH-GITHUB2495** [comment]
The above issue has resolved ....
