### ISSUE TITLE
Add theming options

### ISSUE THREAD

**Issue by ADRE9** [ADRE9/bunk-manager-mern#7]
Dark theme and light theme needs to be integrated

**Comment by AakankshaKamal** [comment]
I am a GSSOC 2021 participant and would like to work on this project. Do we have any groups for discussions related to this?

**Comment by ADRE9** [comment]
We'll soon be starting it. Thanks for asking .

**Comment by subhangi2731** [comment]
can you please assign me this?

**Comment by Abhishek765** [comment]
Hello I would like to work on this I am a Gssoc'21 participant, could you assign this task to me?
And one thing can I set a button at top right corner to add the light and dark theme option??

**Comment by ADRE9** [comment]
@Abhishek765 and @subhangi2731 go ahead fork the project and make use of Theme.js file to change themes. Go through the Material-UI documentation and through my client folder to understand the structure of components.

**Comment by Abhishek765** [comment]
@Mustafiz04 **Please have a Look Without Dark theme**


![image](https://user-images.githubusercontent.com/43133456/111042489-a7656180-8463-11eb-88d4-e66e4a41d934.png)


![image](https://user-images.githubusercontent.com/43133456/111042605-2a86b780-8464-11eb-925e-a9523342c4cf.png)


**With Dark theme**

![image](https://user-images.githubusercontent.com/43133456/111042664-7df90580-8464-11eb-8d6f-8d05e4e524ae.png)


![image](https://user-images.githubusercontent.com/43133456/111042648-6588eb00-8464-11eb-9ed5-9f4eb6fcd5b3.png)

**Comment by Abhishek765** [comment]
One Thing I faced some Issue (I don't know what happened I never change any server code ):  Due to this I am unable to log in Till now the dark theme works well with Auth page and Home page, as the rest of the pages are empty I am not able to add that functionality in those pages (we can add later once all pages are ready ) 
So Can I make a Pull request so that you and the team can review it?

![image](https://user-images.githubusercontent.com/43133456/111042801-23ac7480-8465-11eb-9963-98bd5098418c.png)

**Comment by ADRE9** [comment]
Make a PR. But before I wanted to make sure you used the Theme.js file to implement the dark theme is it? And where do you think on keeping the button to switch the dark theme?

**Comment by Abhishek765** [comment]
> Make a PR. But before I wanted to make sure you used the Theme.js file to implement the dark theme is it? And where do you think on keeping the button to switch the dark theme?

No, I didn't use Theme.js and There is a reason behind that since I used context API to tell the application what is the current theme and sadly we can't use useContext hook inside our Theme.js I tried that but not able to get the theme status in Theme.js So I created my own Context of a theme called 'newTheme' and used in the application anyway I will made a PR and have a look at the file structure and code and let me know if it fine.

**Comment by Abhishek765** [comment]
> > Make a PR. But before I wanted to make sure you used the Theme.js file to implement the dark theme is it? And where do you think on keeping the button to switch the dark theme?
> 
> No, I didn't use Theme.js and There is a reason behind that since I used context API to tell the application what is the current theme and sadly we can't use useContext hook inside our Theme.js I tried that but not able to get the theme status in Theme.js So I created my own Context of a theme called 'newTheme' and used in the application anyway I will made a PR and have a look at the file structure and code and let me know if it fine.

See the file structure and I added two folders `hooks` and `providers`

![image](https://user-images.githubusercontent.com/43133456/111079922-2caf4b80-8522-11eb-83b1-556d5fa1a0de.png)

**Comment by Abhishek765** [comment]
> > Make a PR. But before I wanted to make sure you used the Theme.js file to implement the dark theme is it? And where do you think on keeping the button to switch the dark theme?
> 
> No, I didn't use Theme.js and There is a reason behind that since I used context API to tell the application what is the current theme and sadly we can't use useContext hook inside our Theme.js I tried that but not able to get the theme status in Theme.js So I created my own Context of a theme called 'newTheme' and used in the application anyway I will made a PR and have a look at the file structure and code and let me know if it fine.  And Regarding the button to switch the Theme did you notice the small `moon `and `sun icon` 

![image](https://user-images.githubusercontent.com/43133456/111080075-beb75400-8522-11eb-8e46-12c1bfef41ca.png)

![image](https://user-images.githubusercontent.com/43133456/111080085-ca0a7f80-8522-11eb-8b21-2c06488bdb99.png)

**Comment by Abhishek765** [comment]
Let me know if can make a PR?

**Comment by ADRE9** [comment]
Make it. We'll see if it gonna be merged or not. Nice job Btw. Loved the dark theme colors you have picked. I guess you have reversed teh hue. Isn't it?

**Comment by Abhishek765** [comment]
> Make it. We'll see if it gonna be merged or not. Nice job Btw. Loved the dark theme colors you have picked. I guess you have reversed teh hue. Isn't it?

Check out this #58 Pull request It has two conflicts tell me what should I  do ?

**Comment by Abhishek765** [comment]
@ADRE9 Check this out Done with Dark theme :

![image](https://user-images.githubusercontent.com/43133456/111848707-bf405800-8931-11eb-823d-0e340c193651.png)



![image](https://user-images.githubusercontent.com/43133456/111849131-e186a580-8932-11eb-8f54-f012415e0f11.png)

**Comment by Abhishek765** [comment]
@ADRE9 You can close this issue since it is resolved.
