### ISSUE TITLE
Using Docker to remove the setup hassle!

### ISSUE THREAD

**Issue by jain-rishabh-21** [ADRE9/bunk-manager-mern#70]
**Is your feature request related to a problem? Please describe.**
We can consider using docker to reduce the setup hassle developers!

**Describe the solution you'd like**
This can be an alternative way for setting up keeping the standard way intact!

**Comment by jain-rishabh-21** [comment]
Please assign it to me!
Discord: krackerzzz#4371

**Comment by ADRE9** [comment]
Cool! Go ahead!
