### ISSUE TITLE
Add mongoose event listeners 

### ISSUE THREAD

**Issue by Mustafiz04** [ADRE9/bunk-manager-mern#76]
Required is to add event listeners at DB connection file

   ```
 mongoose.connection.on('connected', () => {
        console.log('DB Connection Established')
    })
```

This is example of event listener when DB is connected.
Also have to add for Disconnected, Re-established, connection closed and throw error while some error occurs.

Have any doubt do ask her freely.
Good Luck.

**Comment by promaroy** [comment]
Can I take up this issue?

**Comment by Mustafiz04** [comment]
Ya sure @promaroy 
I am assigning to you.
