### ISSUE TITLE
About section needs to be added in the landing page menu

### ISSUE THREAD

**Issue by ADRE9** [ADRE9/bunk-manager-mern#8]

**Comment by promaroy** [comment]
Can I work on this as a part of GSSOC '21?

**Comment by ADRE9** [comment]
Sure Go ahead!

**Comment by Ankita297** [comment]
Can i work on this ?

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021
Thank you.

**Comment by srk224** [comment]
Hey . I would like to work on this 
We can add the about page and moreover if you could tell me the details of what to add in that ABOUT page.. I would do that too.
Would love to work on this.
Thanks a lot

**Comment by ADRE9** [comment]
We are for now redesigning the UI/UX of the app so if you have any idea sure pitch it up.

**Comment by nikhilgupta2001** [comment]
I'd like to work on it as a GSSOC'21 participant. Please Assign it to me
