### ISSUE TITLE
Redesigning the UI/UX for the Attendance Page of the app.

### ISSUE THREAD

**Issue by Saptar001** [ADRE9/bunk-manager-mern#89]
In a website of app the UI/UX also plays an important role in engagements. The better the UI of the app the more catchy it is and attracts more users.
I have already designed the Landing Page and I want to redesign and enhance the UI/UX of all the pages of the app .

It would be very nice if you kindly assign me this issue so that I could work on it for GSSOC,21.

**Comment by ADRE9** [comment]
Select a page and start working.

**Comment by ADRE9** [comment]
Which page are you working on? Select one page and update the heading accordingly. And let other work on other pages.

**Comment by Saptar001** [comment]
@ADRE9  I have started to work on the "Attendance Page".
