### ISSUE TITLE
Repositioning Fab Icon in Subject Page.

### ISSUE THREAD

**Issue by Artistic18** [ADRE9/bunk-manager-mern#92]
In the current version the Add Icon is overlapping the grid.
![Untitled](https://user-images.githubusercontent.com/16490253/113195563-0dcdea80-9280-11eb-9f7f-48920452be21.png)

It would be better to reposition and apply a little bit of scaling so that the UI looks cleaner.
After Changes : 
![Untitled2](https://user-images.githubusercontent.com/16490253/113195754-44a40080-9280-11eb-8bd2-cbe4d17715b1.png)

**Comment by ADRE9** [comment]
How do you plan it for mobile devices?

**Comment by Artistic18** [comment]
Yeah sorry I didn't thought about it earlier, it works fine for mobile devices but for higher resolutions it looks odd.

**Comment by ADRE9** [comment]
I mean since the design has not yet been reimagined can you think of implementing the same with fab icon.
