### ISSUE TITLE
[FEATURE] Add Subject Dialog.

### ISSUE THREAD

**Issue by Artistic18** [ADRE9/bunk-manager-mern#93]
Currently clicking the add button redirects us to a new page.
I think it would be better instead of redirecting to new page, we can use a Form Dialog.
![Untitled3](https://user-images.githubusercontent.com/16490253/113196120-c300a280-9280-11eb-9330-f30beff356b2.png)

**Comment by ADRE9** [comment]
Amazing! It looks good to me.

**Comment by Artistic18** [comment]
How does this look? @ADRE9 
https://user-images.githubusercontent.com/16490253/113297527-5933d780-9318-11eb-8bc1-6f4cf48de558.mp4

**Comment by Artistic18** [comment]
How does this look? @ADRE9 

https://user-images.githubusercontent.com/16490253/113297965-eaa34980-9318-11eb-89d4-ced985b4ce1b.mp4

**Comment by ADRE9** [comment]
@Artistic18 perfect🙌🏻.

**Comment by Artistic18** [comment]
I have added the pull request, kindly review it.

**Comment by Artistic18** [comment]
It's responsive.
Below is the screenshot for mobile devices.
![Untitled](https://user-images.githubusercontent.com/16490253/113310030-63a89e00-9325-11eb-9d2a-9afa1ccd2290.png)

**Comment by ADRE9** [comment]
@Artistic18 so this will work thes same edit subject page also , right?. You have reused the modal?

**Comment by Artistic18** [comment]
@ADRE9 At the moment I have only implemented it for the Add functionality, I was thinking to create another issue for Edit functionality and let someone else work on it.

**Comment by ADRE9** [comment]
Yes, go ahead create an issue. I am pretty impressed by your knowledge of Redux .

**Comment by ADRE9** [comment]
Ok one more thing. Clicking outside the modal leaves the route to /subject/new. Make it change to /subject so that clicking outside the user may land back to the subject page.

**Comment by Artistic18** [comment]
Yes Sure working on it

**Comment by Artistic18** [comment]
@ADRE9 Fixed, kindly review the PR.

**Comment by ADRE9** [comment]
Attach a working video too.

**Comment by Artistic18** [comment]
@ADRE9 

https://user-images.githubusercontent.com/16490253/113398399-28a57980-93bc-11eb-9ac5-db4daf298451.mp4
