### ISSUE TITLE
[Design] Create an about page.

### ISSUE THREAD

**Issue by ADRE9** [ADRE9/bunk-manager-mern#96]
**Deliverables:**
Add the deliverables with their description here.
- [x] Design about page in FIGMA or Adobe XD
- [x] Be consistent with the color palette used [here](https://www.figma.com/file/dQbGpSkclUec07vztFkUEV/Material-Design-UI-kit-Components-library-Community?node-id=120%3A1658)
- [x] Ask for reviewing to the Project Admin

**Comment by FireQueen-3010** [comment]
Can I work on this under gssoc'21?

**Comment by ADRE9** [comment]
Yes sure. Make sure you follow the color palette for consistency.Check this out  [Homepage](https://www.figma.com/file/dQbGpSkclUec07vztFkUEV/Material-Design-UI-kit-Components-library-Community?node-id=120%3A1658)

**Comment by FireQueen-3010** [comment]
Yeah sure, thnq!

**Comment by FireQueen-3010** [comment]
Hey, I have a doubt. After working on the design do I just provide the link here or add it among the files in the project? @ADRE9

**Comment by ADRE9** [comment]
First let us review your designs. If it's acceptable you need to make a pr adding the link to your figma or Adobe XD in the readme file. For reviewing send me the link in the discord server.

**Comment by FireQueen-3010** [comment]
Okay

**Comment by FireQueen-3010** [comment]
Done please check discord :) @ADRE9

**Comment by subhangi2731** [comment]
please assign me this

**Comment by ADRE9** [comment]
> please assign me this

Sorry @subhangi2731 this has already been assigned, to another participant who contacted us on discord a week before.

**Comment by Khushi-24** [comment]
@ADRE9 Can I work on this issue if no one is working?

**Comment by ADRE9** [comment]
@Khushi-24 it has already been assigned. Sorry.

**Comment by harshita2319** [comment]
Open now or someone's working?

**Comment by subhangi2731** [comment]
@ADRE9 @kunaljain0212 Please assign me this issue I will send a pr within 2 days

**Comment by ADRE9** [comment]
@subhangi2731 the pr has been merged for it I guess. Sorry for not closing this.
