### ISSUE TITLE
[FEATURE] Edit Dialog

### ISSUE THREAD

**Issue by Artistic18** [ADRE9/bunk-manager-mern#97]
Currently only the Add Subject functionality supports dialog box, the edit functionality still redirects to a new page.

#### Deliverables
- [x] Add support for Dialog box for Edit functionality.

#### The modal should be similar to this :- 
![Untitled](https://user-images.githubusercontent.com/16490253/113336634-55b64580-9344-11eb-8428-4778eec3ffe8.png)

#### Feel free to assign yourself if you want to work on this issue, if no one gets assigned I will work on this issue.

**Comment by Coder-Srinivas** [comment]
Hey @ADRE9 can I work on this issue as a part of GSSOC'21?

**Comment by ADRE9** [comment]
@Coder-Srinivas  go ahead. @Artistic18  has added the add dialogue and I guess it can be reused. So yes you can use the component.

**Comment by Coder-Srinivas** [comment]
@ADRE9 can you tell me about the contents of the dialog?
Should the name of the subject change or only the days and subject type or all?

**Comment by ADRE9** [comment]
@Coder-Srinivas check out the edit subject page of the current commit. It's gonna be same as that.

**Comment by Artistic18** [comment]
@ADRE9 @Coder-Srinivas Yes the component can be reused, you just need to link it properly and do a bit of state modifications.

**Comment by ADRE9** [comment]
@Coder-Srinivas what's the status?

**Comment by Coder-Srinivas** [comment]
@ADRE9 I have a small doubt, messaged you on discord regarding it.

**Comment by Artistic18** [comment]
@Coder-Srinivas are you working on this issue?

**Comment by Artistic18** [comment]
I think no one is working on this issue, I would like to take it.

**Comment by ADRE9** [comment]
Go ahead.

**Comment by Artistic18** [comment]
@ADRE9 check this, I have also modified the form to display the days checked which are already present in days array.

https://user-images.githubusercontent.com/16490253/115117794-ef752800-9fbd-11eb-8993-555bdb99de6f.mp4

**Comment by ADRE9** [comment]
Looks perfect to me. Its responsive like before?

Make a PR if it is else make it responsive.

**Comment by Artistic18** [comment]
@ADRE9 yes I have reused the same modal and modified it.

**Comment by Artistic18** [comment]
@ADRE9 I think I can't push to master because the timetable page has still not been merged with master. So shall I push edit dialog to timetable branch?
